-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "17")

-- Settings
hl.config({
    decoration = {
        blur = {
            xray = false,
        },
    },
    general = {
        allow_tearing = true,
        layout = "scrolling",
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
})

-- Bezier curves
hl.curve("menu_decel", { type = "bezier", points = { {0.1, 1.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 7.0,
    bezier = "menu_decel",
    style = "slide",
})

-- Keybinds
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "right" }))
